// Marketing Plan Section enum matching Prisma schema
export enum MarketingPlanSection {
  FULL_PLAN = 'FULL_PLAN',
  EXECUTIVE_SUMMARY = 'EXECUTIVE_SUMMARY',
  MISSION_STATEMENT = 'MISSION_STATEMENT',
  MARKETING_OBJECTIVES = 'MARKETING_OBJECTIVES',
  SWOT_ANALYSIS = 'SWOT_ANALYSIS',
  MARKET_RESEARCH = 'MARKET_RESEARCH',
  MARKETING_STRATEGY = 'MARKETING_STRATEGY',
  CHALLENGES_SOLUTIONS = 'CHALLENGES_SOLUTIONS',
  EXECUTION = 'EXECUTION',
  BUDGET = 'BUDGET',
  CONCLUSION = 'CONCLUSION',
  FEEDBACK = 'FEEDBACK',
  KEY_PERFORMANCE = 'KEY_PERFORMANCE'
} 